type AttendList{
    id: ID!,
    month: String,
    attendances: [String]
}

input inputAttendList{
    month: String,
    attendances: [String] 
}

type Query{
    getAttendLists: [AttendList]
}

type Mutation{
    saveAttendList(attendList:inputAttendList): AttendList
}