type AttendList {
  id: ID!
  month: String
  attendances: [String]
}

input inputAttendList {
  attendances: [String]
}

type Query {
  getAttendLists(id:String): [AttendList]
}

type Mutation {
  saveAttendList(attendList: inputAttendList): AttendList
}
